### ISSUE TITLE
Soc Limit in Frontend does not autorefresh

### ISSUE THREAD

**Issue by fprucker** [pkuehnel/TeslaSolarCharger#379]
When I set the SoC limit in the Tesla app to 100%, TSC shows (and uses) 80%. If I set it to 99% or less, it correctly shows (and uses) the the set value. Can you reproduce this?

(use case: for a longer trip I want to use TSC to charge to 100% by a certain target date/time)

**Comment by pkuehnel** [comment]
As my car is in Service at least until Friday I can't test right now. Are you talking about this value:
![image](https://user-images.githubusercontent.com/35361981/196131828-81b11951-fb57-4f91-a653-5453e5362cdb.png)

This should be the same as TeslaMate displays it. Does TeslaMate show 100% while TeslaSolarcharger displays 80%?

**Comment by fprucker** [comment]
Exactly that value. Any value aside from 100% is adopted, but if you set it to 100% it shows 80% (or the last value which was different to 100% - have not thoroughly checked this). 

My workaround for now is setting it to 99% :-)

**Comment by pkuehnel** [comment]
Got my car back and tried it out. 100% works for me Without any issues.
When you tried, was `StateString` displayed as `suspended`?
![image](https://user-images.githubusercontent.com/35361981/197348458-8b959660-762d-46e7-bd1a-65dc261896dc.png)

This would mean, that TeslaMate is trying to let the car fall asleep. While this is happening, No changes are deteced. If you still have this issue, please [share your logfiles](https://github.com/pkuehnel/TeslaSolarCharger#generate-logfiles).

**Comment by fprucker** [comment]
Sorry for the late feedback. The problem was that it takes some time for your software /teslamate to pick up the car max SoC setting. After waiting for a minute or two the 100% max SoC appeared in your software and then I also was able to set it to 100% without an error message.

**Comment by pkuehnel** [comment]
TeslaMate refreshes all values from TeslaMate every 10 seconds (if refreshing is not stopped due to TeslaMate letting the car fall asleep). My software refreshes the values immediately after TeslaMate gets new values. The values should be updated in the browser every five seconds, but it looks like this refresh in the browser only occurs for the charge limit if the whole page is refreshed. I will look into it. Note: Charging behavior is not affected by this issue, only the displayed value in the browser is not auto refreshed.

**Comment by pkuehnel** [comment]
This issue will be fixed in the next version.
